# Puerto para Render
server.port=${PORT:8081}

# Configuración de Supabase (PostgreSQL) usando variables de entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Secreto para firmar los tokens JWT
auditn3xt.jwt.secret=${JWT_SECRET}
auditn3xt.jwt.expiration=86400000